# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 773757193c22fb150b7b653202eccdac4d79d93bc94d6d6744bc3478a1836ca3fabbff239fc62f9decf68ec7814d4ba6158768b06ee0ac1764f21f50add4b3bb

test:
  secret_key_base: 343f3ae350c2698d9d89b9c2617a29930575ae32491690e4e17e42ccba6bf6ccc94e42883cba563bb2db0b21cbe964f18afc913c58529af7082f4b706f9080a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
